# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - cinemania1

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Java version
      uses: actions/setup-java@v1
      with:
          java-version: '17'

    - name: Build with Maven
      run: mvn clean install

    - name: Run test with Maven
      run:  mvn test install

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://cinemania1.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_524383fa934c4a04a309f69a6f26a1a0 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_89df3bd805094174a346b89c227cc17d }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: cinemania1.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_524383fa934c4a04a309f69a6f26a1a0 }}/abdullahiisse/cinemania-dockerfile:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'cinemania1'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_83dc1e97c9ec450193bbf3701ce103d3 }}
        images: 'cinemania1.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_524383fa934c4a04a309f69a6f26a1a0 }}/abdullahiisse/cinemania-dockerfile:${{ github.sha }}'
